version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "46483:46483"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data
    command: server /data

  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:80"  # Порт 80 внутри контейнера маппится на порт 8000 на хосте
    depends_on:
      - minio
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password

volumes:
  minio_data: